controller_list:
  - name: fake_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
  - group: manipulator
    pose: zero_pose